embed_dim: 1024
gap_head_num: 1
gap_layer_num: 2
local_channel_dim: 32
pool_head_num: 1
ssl_ckpt: /media/lab2208/ssd/Explainablility/Localization/checkpoints/wavlm_large.pt
ssl_feat_dim: 1024
ssl_name: wavlm_local
